app:
  name: wordpress-app
  group: wordpress
  replicaCount: 1
  container:
    image: wordpress
    tag: latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    hasSecrets: false
  service:
    port: 80
    targetPort: 80
  config:
    WP_ENV: stage
    DB_HOST: localhost
    DB_USER: user
    DB_PASSWORD: password
    DB_NAME: database
    WP_DEBUG: false
    WP_DEBUG_DISPLAY: false
    WP_DEBUG_LOG: false
  ingress:
    basicAuth: false
    tls: false
    hosts:
      - host: wordpress.dev
        paths:
          - path: /
            backend:
              serviceName: wordpress-app
              servicePort: 80

