apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.app.group }}
  labels:
    group: {{ .Values.app.group }}
data:
  {{- range $key, $value := .Values.app.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end}}
